name: MSBuild (Action)

on:
  push:
    paths:
      - .github/actions/msbuild/action.yml
      - .github/workflows/msbuild_action.yml
  workflow_dispatch:

jobs:
  msbuild:
    name: MSBuild
    runs-on: windows-latest
    steps:
      - name: MSBuild
        uses: DynamoDS/workflows/.github/actions/msbuild@master
        with:
          repository: DynamoDS/Dynamo
          dotnet_version: 8.0.x
          solution_path: src\Dynamo.All.sln
          build_configuration: Release
          runtime_identifier: win-x64
      - name: Look for DynamoCLI.exe
        run: |
          Write-Output "***Locating DynamoCLI.exe!***"
          if (Test-Path -Path "${{ github.workspace }}/bin/AnyCPU/Release/DynamoCLI.exe") {
            Write-Output "DynamoCLI.exe exists!"
          } else {
            Write-Error "DynamoCLI.exe was not found!"
          }
